### ISSUE TITLE
Battery percentage request returns something

### ISSUE THREAD

**Issue by mduenas** [SocketMobile/capture-java#2]
When I make a battery level request the integer returned in the callback property looks like a pointer value rather than the percentage. I've inspected the property class and not found the percentage value in any of the 'storage areas'. Wondering if I'm calling the wrong method.

DeviceClient mDevice; (initialized properly of course)
mDevice.getBatteryLevel(propertyCallback); <--This is the call I'm expecting to work

// This is my callback method (which IS being called but the value returned makes no sense)
PropertyCallback propertyCallback = new PropertyCallback() {
        @Override
        public void onComplete(@Nullable CaptureError captureError, @Nullable Property property) {
            if (captureError != null) {
                Log.d("onComplete", String.format("capture error %s", captureError.getMessage()));
            } else {
                if (property != null) {
                    if (property.getId() == DEVICE_BATTERY_LEVEL) {
                        Log.d("onComplete", String.format("property set %d", property.getId()));
                        int percentage = property.getInt();
                        // THIS NUMBER DOESN'T LOOK LIKE A PERCENTAGE 1667739373
                    }
                }
            }
        }
    };

**Comment by socketPM** [comment]
referring to the documentation: https://docs.socketmobile.com/capture/java/en/latest/javadoc/capture/com/socketmobile/capture/client/DeviceClient.html#getbatterylevel

> Queries the battery level of the device

Result is an integer where the four bytes represent

Byte 0 - reserved/empty
Byte 1 - current level
Byte 2 - minimum
Byte 3 - maximum
To calculate the level as a percentage

// Java
int value = property.getInt();
int current = value >>> 8 & 0xFF
int min = value >>> 16 & 0xFF
int max = value >>> 24 & 0xFF
Double batteryPercent = current * 100.0 / (max - min)

// Kotlin
val current = property.int ushr 8 and 0xff
val min = property.int ushr 16 and 0xff
val max = property.int ushr 24 and 0xff
val percentage = current * 100.0 / (max - min)

**Comment by mduenas** [comment]
Thank you!
